output-dir: "{project-root}"
emit:
  - '@azure-tools/typespec-autorest'
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "../resource-manager"
    emitter-output-dir: "{output-dir}"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azuremonitoredge.json"
    examples-directory: ./examples
    new-line: lf
